AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a VPC with public and private subnets, NAT gateway, and EC2 instances.

Resources:
  # Tạo VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC
  
  # Tạo Internet Gateway
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Tạo Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Tạo Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Tạo Route Table cho Public Subnet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Tạo NAT Gateway
  MyNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt MyElasticIP.AllocationId

  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # Tạo Route Table cho Private Subnet
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref MyNATGateway
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # Security Group cho Public EC2 instance
  PublicEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 113.161.91.9/32

  # Security Group cho Private EC2 instance
  PrivateEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Public instance
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicEC2SecurityGroup

  # EC2 Instance trong Public Subnet
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: 
        - !Ref PublicEC2SecurityGroup
      ImageId: ami-0ebfd941bbafe70c6  # AMI ID cần thay thế theo region của bạn

  # EC2 Instance trong Private Subnet
  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds: 
        - !Ref PrivateEC2SecurityGroup
      ImageId: ami-0ebfd941bbafe70c6  # AMI ID cần thay thế theo region của bạn
#Add output 
Outputs:
  VPCID:
    Description: 'ID VPC: '
    Value: !Ref MyVPC
    Export:
      Name: VPCID

  PublicSubnetID:
    Description: 'ID Public Subnet: '
    Value: !Ref PublicSubnet
    Export:
      Name: PublicSubnetID

  PrivateSubnetID:
    Description: 'ID Private Subnet: '
    Value: !Ref PrivateSubnet
    Export:
      Name: PrivateSubnetID

  InternetGatewayID:
    Description: 'ID Internet Gateway: '
    Value: !Ref InternetGateway
    Export:
      Name: InternetGatewayID

  NATGatewayID:
    Description: 'ID NAT Gateway: '
    Value: !Ref NATGateway
    Export:
      Name: NATGatewayID

  PublicInstanceID:
    Description: 'ID Public EC2 Instance: '
    Value: !Ref PublicEC2Instance
    Export:
      Name: PublicInstanceID

  PrivateInstanceID:
    Description: 'ID Private EC2 Instance: '
    Value: !Ref PrivateEC2Instance
    Export:
      Name: PrivateInstanceID

  PublicInstancePublicIP:
    Description: 'Public IP: '
    Value: !GetAtt PublicEC2Instance.PublicIp
    Export:
      Name: PublicInstancePublicIP

  PrivateInstancePrivateIP:
    Description: 'Private IP: '
    Value: !GetAtt PrivateEC2Instance.PrivateIp
    Export:
      Name: PrivateInstancePrivateIP