version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat

  pre_build:
    commands:
      - echo "Running cfn-lint to check CloudFormation template syntax"
      - cfn-lint group_19.yaml  

  build:
    commands:
      - echo "Running Taskcat to test CloudFormation template in multiple regions"
      - taskcat test run --no-delete   

  post_build:
    commands:
      - echo "Build and validation complete"
      
artifacts:
  files:
    - group_19.yaml  
